export * from './error-page/error-page'
export * from './main-page/main-page'
export * from './price-list/price-list'
export * from './service-page/service-page'
export * from './services-page/services-page'
